// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AdminCountSchema - Contains total admin counts for an Unleash instance.
type AdminCountSchema struct {
	// Total number of admins that do not have a password set. May be SSO, but may also be users that did not set a password yet.
	NoPassword float64 `json:"noPassword"`
	// Total number of admins that have a password set.
	Password float64 `json:"password"`
	// Total number of service accounts that have the admin root role.
	Service float64 `json:"service"`
}
