// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Strategies struct {
	// The ID of the environment that the strategy belongs to.
	Environment string `json:"environment"`
	// The ID of the strategy
	FeatureName string `json:"featureName"`
	// The ID of the strategy
	ID string `json:"id"`
	// The ID of the project that the strategy belongs to.
	ProjectID string `json:"projectId"`
	// The name of the strategy's type.
	StrategyName string `json:"strategyName"`
}

func (o *Strategies) GetEnvironment() string {
	if o == nil {
		return ""
	}
	return o.Environment
}

func (o *Strategies) GetFeatureName() string {
	if o == nil {
		return ""
	}
	return o.FeatureName
}

func (o *Strategies) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Strategies) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *Strategies) GetStrategyName() string {
	if o == nil {
		return ""
	}
	return o.StrategyName
}

// AdminStrategiesSchema - A collection of strategies belonging to a specified segment.
type AdminStrategiesSchema struct {
	// The list of strategies
	Strategies []Strategies `json:"strategies"`
}

func (o *AdminStrategiesSchema) GetStrategies() []Strategies {
	if o == nil {
		return []Strategies{}
	}
	return o.Strategies
}
