// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/pkg/utils"
	"time"
)

// Type - The type of API token
type Type string

const (
	TypeClient   Type = "client"
	TypeAdmin    Type = "admin"
	TypeFrontend Type = "frontend"
)

func (e Type) ToPointer() *Type {
	return &e
}

func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "client":
		fallthrough
	case "admin":
		fallthrough
	case "frontend":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// APITokenSchema - An overview of an [Unleash API token](https://docs.getunleash.io/reference/api-tokens-and-client-keys).
type APITokenSchema struct {
	// Alias is no longer in active use and will often be NULL. It's kept around as a way of allowing old proxy tokens created with the old metadata format to keep working.
	Alias *string `json:"alias,omitempty"`
	// When the token was created.
	CreatedAt time.Time `json:"createdAt"`
	// The environment the token has access to. `*` if it has access to all environments.
	Environment *string `json:"environment,omitempty"`
	// The token's expiration date. NULL if the token doesn't have an expiration set.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// The project this token belongs to.
	Project string `json:"project"`
	// The list of projects this token has access to. If the token has access to specific projects they will be listed here. If the token has access to all projects it will be represented as `[*]`
	Projects []string `json:"projects"`
	// The token used for authentication.
	Secret string `json:"secret"`
	// When the token was last seen/used to authenticate with. NULL if the token has not yet been used for authentication.
	SeenAt *time.Time `json:"seenAt,omitempty"`
	// A unique name for this particular token
	TokenName string `json:"tokenName"`
	// The type of API token
	Type Type `json:"type"`
	// This property was deprecated in Unleash v5. Prefer the `tokenName` property instead.
	//
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	Username *string `json:"username,omitempty"`
}

func (a APITokenSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APITokenSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *APITokenSchema) GetAlias() *string {
	if o == nil {
		return nil
	}
	return o.Alias
}

func (o *APITokenSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *APITokenSchema) GetEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *APITokenSchema) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *APITokenSchema) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

func (o *APITokenSchema) GetProjects() []string {
	if o == nil {
		return []string{}
	}
	return o.Projects
}

func (o *APITokenSchema) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}

func (o *APITokenSchema) GetSeenAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.SeenAt
}

func (o *APITokenSchema) GetTokenName() string {
	if o == nil {
		return ""
	}
	return o.TokenName
}

func (o *APITokenSchema) GetType() Type {
	if o == nil {
		return Type("")
	}
	return o.Type
}

func (o *APITokenSchema) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}
