// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/pkg/utils"
)

// ClientMetricsEnvSchema - Used for reporting feature evaluation results from SDKs
type ClientMetricsEnvSchema struct {
	AdditionalProperties interface{} `additionalProperties:"true" json:"-"`
	// The name of the application the SDK is being used in
	AppName string `json:"appName"`
	// Which environment the SDK is being used in
	Environment string `json:"environment"`
	// Name of the feature checked by the SDK
	FeatureName string `json:"featureName"`
	// How many times the toggle evaluated to false
	No        *int64      `json:"no,omitempty"`
	Timestamp *DateSchema `json:"timestamp,omitempty"`
	// How many times each variant was returned
	Variants map[string]int64 `json:"variants,omitempty"`
	// How many times the toggle evaluated to true
	Yes *int64 `json:"yes,omitempty"`
}

func (c ClientMetricsEnvSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientMetricsEnvSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClientMetricsEnvSchema) GetAdditionalProperties() interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *ClientMetricsEnvSchema) GetAppName() string {
	if o == nil {
		return ""
	}
	return o.AppName
}

func (o *ClientMetricsEnvSchema) GetEnvironment() string {
	if o == nil {
		return ""
	}
	return o.Environment
}

func (o *ClientMetricsEnvSchema) GetFeatureName() string {
	if o == nil {
		return ""
	}
	return o.FeatureName
}

func (o *ClientMetricsEnvSchema) GetNo() *int64 {
	if o == nil {
		return nil
	}
	return o.No
}

func (o *ClientMetricsEnvSchema) GetTimestamp() *DateSchema {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *ClientMetricsEnvSchema) GetVariants() map[string]int64 {
	if o == nil {
		return nil
	}
	return o.Variants
}

func (o *ClientMetricsEnvSchema) GetYes() *int64 {
	if o == nil {
		return nil
	}
	return o.Yes
}
