// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContextFieldStrategiesSchema - A wrapper object containing all strategies that use a specific context field
type ContextFieldStrategiesSchema struct {
	// List of strategies using the context field
	Strategies []ContextFieldStrategiesSchemaStrategiesInner `json:"strategies"`
}
