// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ExportResultSchemaSegmentsInner struct {
	ID   float64 `json:"id"`
	Name *string `json:"name,omitempty"`
}
