// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
)

type MarkNotificationsAsReadSchema struct {
	Notifications []float64 `json:"notifications"`

	AdditionalProperties interface{} `json:"-"`
}
type _MarkNotificationsAsReadSchema MarkNotificationsAsReadSchema

func (c *MarkNotificationsAsReadSchema) UnmarshalJSON(bs []byte) error {
	data := _MarkNotificationsAsReadSchema{}

	if err := json.Unmarshal(bs, &data); err != nil {
		return err
	}
	*c = MarkNotificationsAsReadSchema(data)

	additionalFields := make(map[string]interface{})

	if err := json.Unmarshal(bs, &additionalFields); err != nil {
		return err
	}
	delete(additionalFields, "notifications")

	c.AdditionalProperties = additionalFields

	return nil
}

func (c MarkNotificationsAsReadSchema) MarshalJSON() ([]byte, error) {
	out := map[string]interface{}{}
	bs, err := json.Marshal(_MarkNotificationsAsReadSchema(c))
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	bs, err = json.Marshal(c.AdditionalProperties)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	return json.Marshal(out)
}
