// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"terraform/internal/sdk/pkg/utils"
	"time"
)

// ProjectSchemaMode - The project's [collaboration mode](https://docs.getunleash.io/reference/project-collaboration-mode). Determines whether non-project members can submit change requests or not.
type ProjectSchemaMode string

const (
	ProjectSchemaModeOpen      ProjectSchemaMode = "open"
	ProjectSchemaModeProtected ProjectSchemaMode = "protected"
)

func (e ProjectSchemaMode) ToPointer() *ProjectSchemaMode {
	return &e
}

func (e *ProjectSchemaMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open":
		fallthrough
	case "protected":
		*e = ProjectSchemaMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectSchemaMode: %v", v)
	}
}

// ProjectSchema - A definition of the project used for projects listing purposes
type ProjectSchema struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// A default stickiness for the project affecting the default stickiness value for variants and Gradual Rollout strategy
	DefaultStickiness *string `json:"defaultStickiness,omitempty"`
	// Additional information about the project
	Description *string `json:"description,omitempty"`
	// `true` if the project was favorited, otherwise `false`.
	Favorite *bool `json:"favorite,omitempty"`
	// The number of features this project has
	FeatureCount *float64 `json:"featureCount,omitempty"`
	// An indicator of the [project's health](https://docs.getunleash.io/reference/technical-debt#health-rating) on a scale from 0 to 100
	Health *float64 `json:"health,omitempty"`
	// The id of this project
	ID string `json:"id"`
	// The number of members this project has
	MemberCount *float64 `json:"memberCount,omitempty"`
	// The project's [collaboration mode](https://docs.getunleash.io/reference/project-collaboration-mode). Determines whether non-project members can submit change requests or not.
	Mode *ProjectSchemaMode `json:"mode,omitempty"`
	// The name of this project
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (p ProjectSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProjectSchema) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *ProjectSchema) GetDefaultStickiness() *string {
	if o == nil {
		return nil
	}
	return o.DefaultStickiness
}

func (o *ProjectSchema) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProjectSchema) GetFavorite() *bool {
	if o == nil {
		return nil
	}
	return o.Favorite
}

func (o *ProjectSchema) GetFeatureCount() *float64 {
	if o == nil {
		return nil
	}
	return o.FeatureCount
}

func (o *ProjectSchema) GetHealth() *float64 {
	if o == nil {
		return nil
	}
	return o.Health
}

func (o *ProjectSchema) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ProjectSchema) GetMemberCount() *float64 {
	if o == nil {
		return nil
	}
	return o.MemberCount
}

func (o *ProjectSchema) GetMode() *ProjectSchemaMode {
	if o == nil {
		return nil
	}
	return o.Mode
}

func (o *ProjectSchema) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ProjectSchema) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
