// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResetPasswordSchema - resetPasswordSchema
type ResetPasswordSchema struct {
	ResetPasswordURL string `json:"resetPasswordUrl"`
}
