// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ServiceAccountsSchema - Represents a list of service accounts, and includes a list of root roles they reference
type ServiceAccountsSchema struct {
	// A list of root roles that are referenced from service account objects in the `serviceAccounts` list
	RootRoles []RoleSchema `json:"rootRoles,omitempty"`
	// A list of service accounts
	ServiceAccounts []ServiceAccountSchema `json:"serviceAccounts"`
}
