// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SetStrategySortOrderSchema - A strategy with its new sort order
type SetStrategySortOrderSchema struct {
	// The ID of the strategy
	ID string `json:"id"`
	// The new sort order of the strategy
	SortOrder float64 `json:"sortOrder"`
}
