// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TagsBulkAddSchema - Represents tag changes to be applied to a list of features.
type TagsBulkAddSchema struct {
	// The list of features that will be affected by the tag changes.
	Features []string `json:"features"`
	// Represents a set of changes to a feature's tags, such as adding or removing tags.
	Tags UpdateTagsSchema `json:"tags"`
}
