// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TagsSchema - A list of tags with a version number
type TagsSchema struct {
	// A list of tags.
	Tags []TagSchema `json:"tags"`
	// The version of the schema used to model the tags.
	Version int64 `json:"version"`
}

func (o *TagsSchema) GetTags() []TagSchema {
	if o == nil {
		return []TagSchema{}
	}
	return o.Tags
}

func (o *TagsSchema) GetVersion() int64 {
	if o == nil {
		return 0
	}
	return o.Version
}
