// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ToggleMaintenanceSchema - toggleMaintenanceSchema
type ToggleMaintenanceSchema struct {
	Enabled bool `json:"enabled"`
}
