// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateTagsSchema - Represents a set of changes to a feature's tags, such as adding or removing tags.
type UpdateTagsSchema struct {
	// Tags to add to the feature.
	AddedTags []TagSchema `json:"addedTags"`
	// Tags to remove from the feature.
	RemovedTags []TagSchema `json:"removedTags"`
}

func (o *UpdateTagsSchema) GetAddedTags() []TagSchema {
	if o == nil {
		return []TagSchema{}
	}
	return o.AddedTags
}

func (o *UpdateTagsSchema) GetRemovedTags() []TagSchema {
	if o == nil {
		return []TagSchema{}
	}
	return o.RemovedTags
}
