// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidateProjectSchema struct {
	ID string `json:"id"`
}

func (o *ValidateProjectSchema) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
