// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// VariantFlagSchema - A representation of an evaluated Unleash feature variant.
type VariantFlagSchema struct {
	// Whether the variant is enabled or not.
	Enabled *bool `json:"enabled,omitempty"`
	// The name of the variant. Will always be disabled if `enabled` is false.
	Name *string `json:"name,omitempty"`
	// Additional data associated with this variant.
	Payload *VariantFlagSchemaPayload `json:"payload,omitempty"`
}
