// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AddFavoriteProjectRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

// AddFavoriteProject404ApplicationJSON - The requested resource was not found.
type AddFavoriteProject404ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

// AddFavoriteProject401ApplicationJSON - Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
type AddFavoriteProject401ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

type AddFavoriteProjectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
	AddFavoriteProject401ApplicationJSONObject *AddFavoriteProject401ApplicationJSON
	// The requested resource was not found.
	AddFavoriteProject404ApplicationJSONObject *AddFavoriteProject404ApplicationJSON
}
