// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AddRoleToUserRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	RoleID    string `pathParam:"style=simple,explode=false,name=roleId"`
	UserID    string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *AddRoleToUserRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *AddRoleToUserRequest) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

func (o *AddRoleToUserRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type AddRoleToUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddRoleToUserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddRoleToUserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddRoleToUserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
