// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type AddTagToFeaturesRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	// tagsBulkAddSchema
	TagsBulkAddSchema shared.TagsBulkAddSchema `request:"mediaType=application/json"`
}

func (o *AddTagToFeaturesRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *AddTagToFeaturesRequest) GetTagsBulkAddSchema() shared.TagsBulkAddSchema {
	if o == nil {
		return shared.TagsBulkAddSchema{}
	}
	return o.TagsBulkAddSchema
}

// AddTagToFeatures415ApplicationJSON - The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
type AddTagToFeatures415ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeatures415ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeatures415ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeatures415ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeatures404ApplicationJSON - The requested resource was not found.
type AddTagToFeatures404ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeatures404ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeatures404ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeatures404ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeatures403ApplicationJSON - The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
type AddTagToFeatures403ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeatures403ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeatures403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeatures403ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeatures401ApplicationJSON - Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
type AddTagToFeatures401ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeatures401ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeatures401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeatures401ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type AddTagToFeaturesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
	AddTagToFeatures401ApplicationJSONObject *AddTagToFeatures401ApplicationJSON
	// The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
	AddTagToFeatures403ApplicationJSONObject *AddTagToFeatures403ApplicationJSON
	// The requested resource was not found.
	AddTagToFeatures404ApplicationJSONObject *AddTagToFeatures404ApplicationJSON
	// The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
	AddTagToFeatures415ApplicationJSONObject *AddTagToFeatures415ApplicationJSON
}

func (o *AddTagToFeaturesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddTagToFeaturesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddTagToFeaturesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AddTagToFeaturesResponse) GetAddTagToFeatures401ApplicationJSONObject() *AddTagToFeatures401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AddTagToFeatures401ApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetAddTagToFeatures403ApplicationJSONObject() *AddTagToFeatures403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AddTagToFeatures403ApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetAddTagToFeatures404ApplicationJSONObject() *AddTagToFeatures404ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AddTagToFeatures404ApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetAddTagToFeatures415ApplicationJSONObject() *AddTagToFeatures415ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AddTagToFeatures415ApplicationJSONObject
}
