// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/pkg/models/shared"
	"net/http"
)

type AddTagToFeaturesRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	// tagsBulkAddSchema
	TagsBulkAddSchema shared.TagsBulkAddSchema `request:"mediaType=application/json"`
}

func (o *AddTagToFeaturesRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *AddTagToFeaturesRequest) GetTagsBulkAddSchema() shared.TagsBulkAddSchema {
	if o == nil {
		return shared.TagsBulkAddSchema{}
	}
	return o.TagsBulkAddSchema
}

// AddTagToFeaturesTagsResponse415ResponseBody - The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
type AddTagToFeaturesTagsResponse415ResponseBody struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeaturesTagsResponse415ResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeaturesTagsResponse415ResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeaturesTagsResponse415ResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeaturesTagsResponseResponseBody - The requested resource was not found.
type AddTagToFeaturesTagsResponseResponseBody struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeaturesTagsResponseResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeaturesTagsResponseResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeaturesTagsResponseResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeaturesTagsResponseBody - The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
type AddTagToFeaturesTagsResponseBody struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeaturesTagsResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeaturesTagsResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeaturesTagsResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// AddTagToFeaturesResponseBody - Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
type AddTagToFeaturesResponseBody struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *AddTagToFeaturesResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddTagToFeaturesResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *AddTagToFeaturesResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type AddTagToFeaturesResponse struct {
	// Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
	FourHundredAndOneApplicationJSONObject *AddTagToFeaturesResponseBody
	// The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
	FourHundredAndThreeApplicationJSONObject *AddTagToFeaturesTagsResponseBody
	// The requested resource was not found.
	FourHundredAndFourApplicationJSONObject *AddTagToFeaturesTagsResponseResponseBody
	// The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
	FourHundredAndFifteenApplicationJSONObject *AddTagToFeaturesTagsResponse415ResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddTagToFeaturesResponse) GetFourHundredAndOneApplicationJSONObject() *AddTagToFeaturesResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOneApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetFourHundredAndThreeApplicationJSONObject() *AddTagToFeaturesTagsResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetFourHundredAndFourApplicationJSONObject() *AddTagToFeaturesTagsResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetFourHundredAndFifteenApplicationJSONObject() *AddTagToFeaturesTagsResponse415ResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFifteenApplicationJSONObject
}

func (o *AddTagToFeaturesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddTagToFeaturesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddTagToFeaturesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
