// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CloneEnvironmentRequest struct {
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (o *CloneEnvironmentRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// CloneEnvironment401ApplicationJSON - Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
type CloneEnvironment401ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CloneEnvironment401ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CloneEnvironment401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CloneEnvironment401ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// CloneEnvironment400ApplicationJSON - The request data does not match what we expect.
type CloneEnvironment400ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CloneEnvironment400ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CloneEnvironment400ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CloneEnvironment400ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type CloneEnvironmentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The request data does not match what we expect.
	CloneEnvironment400ApplicationJSONObject *CloneEnvironment400ApplicationJSON
	// Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
	CloneEnvironment401ApplicationJSONObject *CloneEnvironment401ApplicationJSON
}

func (o *CloneEnvironmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CloneEnvironmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CloneEnvironmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CloneEnvironmentResponse) GetCloneEnvironment400ApplicationJSONObject() *CloneEnvironment400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CloneEnvironment400ApplicationJSONObject
}

func (o *CloneEnvironmentResponse) GetCloneEnvironment401ApplicationJSONObject() *CloneEnvironment401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CloneEnvironment401ApplicationJSONObject
}
