// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

// CreateServiceAccount415ApplicationJSON - The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
type CreateServiceAccount415ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CreateServiceAccount415ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateServiceAccount415ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateServiceAccount415ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// CreateServiceAccount409ApplicationJSON - The provided resource can not be created or updated because it would conflict with the current state of the resource or with an already existing resource, respectively.
type CreateServiceAccount409ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CreateServiceAccount409ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateServiceAccount409ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateServiceAccount409ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// CreateServiceAccount403ApplicationJSON - The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
type CreateServiceAccount403ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CreateServiceAccount403ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateServiceAccount403ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateServiceAccount403ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// CreateServiceAccount401ApplicationJSON - Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
type CreateServiceAccount401ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CreateServiceAccount401ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateServiceAccount401ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateServiceAccount401ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// CreateServiceAccount400ApplicationJSON - The request data does not match what we expect.
type CreateServiceAccount400ApplicationJSON struct {
	// The ID of the error instance
	ID *string `json:"id,omitempty"`
	// A description of what went wrong.
	Message *string `json:"message,omitempty"`
	// The name of the error kind
	Name *string `json:"name,omitempty"`
}

func (o *CreateServiceAccount400ApplicationJSON) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateServiceAccount400ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateServiceAccount400ApplicationJSON) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type CreateServiceAccountResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The request data does not match what we expect.
	CreateServiceAccount400ApplicationJSONObject *CreateServiceAccount400ApplicationJSON
	// Authorization information is missing or invalid. Provide a valid API token as the `authorization` header, e.g. `authorization:*.*.my-admin-token`.
	CreateServiceAccount401ApplicationJSONObject *CreateServiceAccount401ApplicationJSON
	// The provided user credentials are valid, but the user does not have the necessary permissions to perform this operation
	CreateServiceAccount403ApplicationJSONObject *CreateServiceAccount403ApplicationJSON
	// The provided resource can not be created or updated because it would conflict with the current state of the resource or with an already existing resource, respectively.
	CreateServiceAccount409ApplicationJSONObject *CreateServiceAccount409ApplicationJSON
	// The operation does not support request payloads of the provided type. Please ensure that you're using one of the listed payload types and that you have specified the right content type in the "content-type" header.
	CreateServiceAccount415ApplicationJSONObject *CreateServiceAccount415ApplicationJSON
	// The resource was successfully created.
	ServiceAccountSchema *shared.ServiceAccountSchema
}

func (o *CreateServiceAccountResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateServiceAccountResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateServiceAccountResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateServiceAccountResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateServiceAccountResponse) GetCreateServiceAccount400ApplicationJSONObject() *CreateServiceAccount400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateServiceAccount400ApplicationJSONObject
}

func (o *CreateServiceAccountResponse) GetCreateServiceAccount401ApplicationJSONObject() *CreateServiceAccount401ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateServiceAccount401ApplicationJSONObject
}

func (o *CreateServiceAccountResponse) GetCreateServiceAccount403ApplicationJSONObject() *CreateServiceAccount403ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateServiceAccount403ApplicationJSONObject
}

func (o *CreateServiceAccountResponse) GetCreateServiceAccount409ApplicationJSONObject() *CreateServiceAccount409ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateServiceAccount409ApplicationJSONObject
}

func (o *CreateServiceAccountResponse) GetCreateServiceAccount415ApplicationJSONObject() *CreateServiceAccount415ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.CreateServiceAccount415ApplicationJSONObject
}

func (o *CreateServiceAccountResponse) GetServiceAccountSchema() *shared.ServiceAccountSchema {
	if o == nil {
		return nil
	}
	return o.ServiceAccountSchema
}
