// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetContextFieldRequest struct {
	ContextField string `pathParam:"style=simple,explode=false,name=contextField"`
}

type GetContextFieldResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// contextFieldSchema
	ContextFieldSchema *shared.ContextFieldSchema
}
