// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type GetProjectUsersRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

type GetProjectUsersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// projectUsersSchema
	ProjectUsersSchema *shared.ProjectUsersSchema
}
