// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveRoleFromGroupRequest struct {
	GroupID   string `pathParam:"style=simple,explode=false,name=groupId"`
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	RoleID    string `pathParam:"style=simple,explode=false,name=roleId"`
}

type RemoveRoleFromGroupResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
